apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infrastructure/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: dauterr/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*'
            dest: .
    - image: dauterr/comments
      context: comments
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*'
            dest: .
    - image: dauterr/events-bus
      context: events-bus
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*'
            dest: .
    - image: dauterr/moderation
      context: moderation
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*'
            dest: .
    - image: dauterr/posts
      context: posts
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*'
            dest: .
    - image: dauterr/query
      context: query
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*'
            dest: .
